#!/usr/bin/env pvpython
"""
Leading-order blowup core of "Finite Time Blowup for Navier-Stokes" (OPENAI, 2026),
Sections 2.1 and 3.1, written as a VTK image file for ParaView.

This is NOT the paper's solution.  Its profiles E, U, V0 are constructed in
Appendices A-C (analytic near the axis, moment-matched to the heat exterior,
then bent to satisfy the admissible stress cone condition) and never appear in
closed form.  What is reproduced here is the *representation* of Section 3.1,

    u_theta = q^-A  E(X),      u_z = q^-A U(X,eta),      r u_r = V0(X,eta),
    p       = q^-2A Pi(X),

    z = q^D eta,     tau = q (1 - eta^2),     X = r^2/(2q),
    A = 1/2 + h,     D = 1/2 - h,             0 < h < 1/100,

with explicit profiles chosen to satisfy every structural constraint that
Section 3.1 states:

  * E/sqrt(2X), U and V0/X are smooth at X = 0, so the Cartesian field is
    smooth on the axis for t < 1;
  * E > 0 for X > 0, and E = c_inf X^(-1/2-h) (1 + O(1/X)) as X -> infinity;
  * U = V0 = 0 outside a fixed interval in X (the flow is purely azimuthal
    beyond it, as in the heat exterior);
  * u_z takes the sign of z away from a dividing layer near z = 0, with a small
    upward bias so that u_z(r, 0) != 0 -- the deliberate asymmetry of Sec. 2.1;
  * the poloidal part is generated by a Stokes streamfunction, so the field is
    divergence free identically, not just to discretisation order;
  * d_r p = u_theta^2 / r, i.e. pressure supplies the centripetal force.

The scaling laws of Section 3.1 therefore hold exactly:

    l_r ~ tau^1/2,   l_z ~ tau^(1/2-h),   |u_theta|, |u_z| ~ tau^(-1/2-h),
    |u_r| = O(tau^-1/2),   E_kin ~ tau^(1/2-3h) -> 0.

Output is XDMF2 (https://www.xdmf.org) plus flat little-endian float32
".raw" companions, following the conventions in /u/xdmf: a 3DCoRectMesh
topology with ORIGIN_DXDYDZ geometry, node-centred attributes, and the profile
constants carried along as <Information> elements.  Needs only numpy and scipy.

Usage:
    python ns_core.py --t 0.9 --n 161 -o out/core.xdmf2
    python ns_core.py --series             # a temporal collection, for animation
    python /u/xdmf/valid.py /u/xdmf/Xdmf.dtd out/*.xdmf2
"""

import argparse
import io
import os

import numpy as np
from scipy.optimize import brentq


# ----------------------------------------------------------------------------
# similarity coordinates:  q - z^2 q^(2h) = tau
# ----------------------------------------------------------------------------

def solve_q(zvals, tau, h):
    """The unique q > 0 with q - z^2 q^(2h) = tau, for each z.

    Uniqueness is Lemma 4.1: d/dq (q - z^2 q^2h) = 1 - 2h eta^2 >= 1 - 2h > 0
    on |eta| < 1.  Note q >= tau always, and eta^2 = 1 - tau/q < 1 follows.
    """
    z = np.atleast_1d(np.asarray(zvals, dtype=float))
    q = np.empty(z.shape, dtype=float)
    for i, zi in enumerate(z.ravel()):
        z2 = zi * zi
        if z2 == 0.0:
            q.flat[i] = tau
            continue
        f = lambda Q: Q - z2 * Q ** (2.0 * h) - tau
        hi = max(tau, 1.0)
        while f(hi) <= 0.0:
            hi *= 2.0
        # f(tau) = -z2 tau^2h < 0 < f(hi)
        q.flat[i] = brentq(f, tau, hi, xtol=1e-16, rtol=8.9e-16, maxiter=200)
    return q


# ----------------------------------------------------------------------------
# profile building blocks
# ----------------------------------------------------------------------------

def bump(s):
    """C^infinity, bump(0) = 1, support |s| < 1.  Gives U = V0 = 0 for X >= Xout."""
    out = np.zeros_like(s)
    m = np.abs(s) < 1.0
    out[m] = np.exp(1.0 - 1.0 / (1.0 - s[m] ** 2))
    return out


def dbump(s):
    """d/ds bump(s)."""
    out = np.zeros_like(s)
    m = np.abs(s) < 1.0
    sm = s[m]
    d = 1.0 - sm ** 2
    out[m] = np.exp(1.0 - 1.0 / d) * (-2.0 * sm / d ** 2)
    return out


class Profiles:
    """Fixed profile choices.  All are set before q goes to zero, as in Sec. 3.6."""

    def __init__(self, h=0.01, Xout=0.12, Xe=0.12, Ce=1.0, Cpsi=1.0,
                 eta0=0.14, eta1=0.55, bias=0.16):
        self.h = h
        self.A = 0.5 + h
        self.D = 0.5 - h
        self.Xout = Xout      # edge of the poloidal (inflow/outflow) region in X
        self.Xe = Xe          # swirl core width in X
        self.Ce = Ce          # swirl amplitude
        self.Cpsi = Cpsi      # streamfunction amplitude
        self.eta0 = eta0      # thickness of the dividing layer near z = 0
        self.eta1 = eta1      # axial extent of the jet in eta
        self.bias = bias      # upward bias: u_z(r,0) != 0  (Sec. 2.1)

    # --- swirl -------------------------------------------------------------
    def E(self, X):
        """E(X) = Ce sqrt(2X) (1 + 2X/Xe)^-(1+h).

        E/sqrt(2X) is smooth and positive at X = 0, and
        E -> Ce sqrt(2) Xe^(1+h) (2X)^(-1/2-h) as X -> infinity,
        which is the exterior law E = c_inf X^(-1/2-h) of Sec. 3.1.
        """
        return self.Ce * np.sqrt(2.0 * X) / (1.0 + 2.0 * X / self.Xe) ** (1.0 + self.h)

    def c_inf(self):
        """The constant c_inf > 0 in E = c_inf X^(-1/2-h) (1 + O(1/X))."""
        return self.Ce * np.sqrt(2.0) * (self.Xe / 2.0) ** (1.0 + self.h) * 2.0 ** (-0.5 - self.h) * 2.0 ** (1.0 + self.h)

    def Pi(self, X):
        """Pi(X) = -int_X^inf E^2/(2x) dx, in closed form for this E."""
        h, Xe, Ce = self.h, self.Xe, self.Ce
        return -(Ce ** 2) * Xe / (2.0 * (1.0 + 2.0 * h)) \
            * (1.0 + 2.0 * X / Xe) ** (-1.0 - 2.0 * h)

    def eta_star(self):
        """The dividing layer: the eta where u_z vanishes, tanh(eta/eta0)+bias=0.

        It sits slightly BELOW z = 0 for bias > 0.  Streamlines cannot cross it.
        """
        return -self.eta0 * np.arctanh(self.bias)

    # --- axial shape -------------------------------------------------------
    def g(self, eta):
        """Axial shape: sign of z away from a thin layer at z = 0, plus a bias."""
        return (np.tanh(eta / self.eta0) + self.bias) \
            * np.exp(-(eta / self.eta1) ** 4)

    def dg(self, eta):
        t = np.tanh(eta / self.eta0)
        w = np.exp(-(eta / self.eta1) ** 4)
        return (1.0 - t * t) / self.eta0 * w \
            + (t + self.bias) * w * (-4.0 * eta ** 3 / self.eta1 ** 4)


# ----------------------------------------------------------------------------
# the field, singularity-free at the axis
#
#   Stokes streamfunction   psi = q^(1-A) Psi(X, eta),   Psi = Cpsi X B(X/Xout) g(eta)
#   G := psi / r^2 = (Cpsi/2) q^-A B(X/Xout) g(eta)      (finite everywhere)
#   u_r = -r dG/dz,   u_z = 2G + r dG/dr                 (exactly div-free)
#
# We return u_r/r and u_theta/r rather than u_r, u_theta, so the Cartesian
# components never divide by r.
# ----------------------------------------------------------------------------

def cyl_fields(r, z, tau, pr):
    """Return (u_r/r, u_theta/r, u_z, p, X, eta, q) on arrays r, z of equal shape."""
    h, A, D = pr.h, pr.A, pr.D
    q = solve_q(z, tau, h)

    X = r * r / (2.0 * q)
    eta = z / q ** D
    s = X / pr.Xout

    B = bump(s)
    dB = dbump(s)
    g = pr.g(eta)
    dg = pr.dg(eta)

    K = 0.5 * pr.Cpsi
    qmA = q ** (-A)
    G = K * qmA * B * g

    # dq/dz = 2 z q^2h / (1 - 2h eta^2)   (differentiate q - z^2 q^2h = tau)
    qp = 2.0 * z * q ** (2.0 * h) / (1.0 - 2.0 * h * eta ** 2)
    dXdz = -(X / q) * qp
    detadz = q ** (-D) * (1.0 - D * eta * qp / q)

    dGdz = K * (-A * q ** (-A - 1.0) * qp * B * g
                + qmA * (dB * dXdz / pr.Xout * g + B * dg * detadz))

    urr = -dGdz                                  # u_r / r
    uz = 2.0 * G + K * qmA * dB * (2.0 * X / pr.Xout) * g   # = 2G + r dG/dr
    utr = pr.Ce * q ** (-A - 0.5) \
        / (1.0 + 2.0 * X / pr.Xe) ** (1.0 + h)   # u_theta / r
    p = q ** (-2.0 * A) * pr.Pi(X)

    return urr, utr, uz, p, X, eta, q


# ----------------------------------------------------------------------------
# XDMF2 output (see /u/xdmf)
#
# XDMF orders structured dimensions slowest-first, so a 3DCoRectMesh carries
# Dimensions="nz ny nx" and ORIGIN_DXDYDZ carries (z, y, x) triples.  Our numpy
# blocks are already C-ordered as [nz, ny, nx] (vector component fastest),
# which is byte-for-byte the layout XDMF expects.
# ----------------------------------------------------------------------------

DTYPE = np.dtype("<f4")            # Endian="Little" NumberType="Float"
PRECISION = DTYPE.itemsize         # the DTD allows Precision 1, 4 or 8

ATTRS = (("u", 3), ("speed", 1), ("u_theta", 1), ("p", 1), ("X", 1),
         ("eta", 1))


def write_raw(path, arr):
    """Dump one array as flat little-endian float32.  Returns its size."""
    a = np.ascontiguousarray(arr, dtype=DTYPE)
    a.tofile(path)
    return a.nbytes


def grid_xml(stem, nx, ny, nz, origin, spacing, info, tval=None, ind="    "):
    """One <Grid> element.  Child order follows the DTD:
    Information*, Time*, Grid*, Topology*, Geometry*, Attribute*."""
    o = io.StringIO()
    w = o.write
    w(f"{ind}<Grid>\n")
    for k, v in info.items():
        w(f'{ind}  <Information\n{ind}      Name="{k}"\n'
          f'{ind}      Value="{v!r}"/>\n')
    if tval is not None:
        w(f'{ind}  <Time\n{ind}      Value="{tval!r}"/>\n')
    w(f'{ind}  <Topology\n'
      f'{ind}      TopologyType="3DCoRectMesh"\n'
      f'{ind}      Dimensions="{nz} {ny} {nx}"/>\n')
    w(f'{ind}  <Geometry\n{ind}      GeometryType="ORIGIN_DXDYDZ">\n')
    for triple in (origin, spacing):
        w(f'{ind}    <DataItem\n{ind}        Dimensions="3">\n')
        for c in triple:
            w(f"{ind}      {c!r}\n")
        w(f"{ind}    </DataItem>\n")
    w(f"{ind}  </Geometry>\n")
    for name, ncomp in ATTRS:
        atype = "Vector" if ncomp == 3 else "Scalar"
        dims = f"{nz} {ny} {nx} 3" if ncomp == 3 else f"{nz} {ny} {nx}"
        w(f'{ind}  <Attribute\n'
          f'{ind}      Name="{name}"\n'
          f'{ind}      Center="Node"\n'
          f'{ind}      AttributeType="{atype}">\n'
          f'{ind}    <DataItem\n'
          f'{ind}        Format="Binary"\n'
          f'{ind}        NumberType="Float"\n'
          f'{ind}        Precision="{PRECISION}"\n'
          f'{ind}        Endian="Little"\n'
          f'{ind}        Dimensions="{dims}">\n'
          f"{ind}      {stem}.{name}.raw\n"
          f"{ind}    </DataItem>\n"
          f"{ind}  </Attribute>\n")
    w(f"{ind}</Grid>\n")
    return o.getvalue()


def evaluate(tau, pr, n=161, Xmax_fac=1.6, eta_max=0.95):
    """Sample the field on a Cartesian block sized to the core at this time."""
    Rmax = np.sqrt(2.0 * Xmax_fac * pr.Xout * tau)
    Zmax = eta_max * tau ** pr.D

    nx = ny = nz = int(n)
    x = np.linspace(-Rmax, Rmax, nx)
    y = np.linspace(-Rmax, Rmax, ny)
    zc = np.linspace(-Zmax, Zmax, nz)

    blocks = {"u": np.empty((nz, ny, nx, 3), dtype=DTYPE)}
    for name, ncomp in ATTRS:
        if ncomp == 1:
            blocks[name] = np.empty((nz, ny, nx), dtype=DTYPE)

    XG, YG = np.meshgrid(x, y, indexing="xy")
    RG = np.sqrt(XG * XG + YG * YG)

    for k, zk in enumerate(zc):
        ZG = np.full_like(RG, zk)
        urr, utr, uz, p, Xa, eta, q = cyl_fields(RG, ZG, tau, pr)
        ux = urr * XG - utr * YG
        uy = urr * YG + utr * XG
        blocks["u"][k, :, :, 0] = ux
        blocks["u"][k, :, :, 1] = uy
        blocks["u"][k, :, :, 2] = uz
        blocks["speed"][k] = np.sqrt(ux * ux + uy * uy + uz * uz)
        blocks["u_theta"][k] = utr * RG
        blocks["p"][k] = p
        blocks["X"][k] = Xa
        blocks["eta"][k] = eta

    return blocks, x, y, zc, Rmax, Zmax


def build_xdmf(path, tau, pr, n=161, Xmax_fac=1.6, eta_max=0.95,
               tval=None, verbose=True):
    """Write <path> (.xdmf2) and its .raw companions.  Returns the <Grid> XML."""
    blocks, x, y, zc, Rmax, Zmax = evaluate(tau, pr, n, Xmax_fac, eta_max)
    nx, ny, nz = len(x), len(y), len(zc)

    d = os.path.dirname(os.path.abspath(path)) or "."
    os.makedirs(d, exist_ok=True)
    stem = os.path.basename(path)
    for suffix in (".xdmf2", ".xdmf", ".xmf"):
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
            break

    nbytes = 0
    for name, _ in ATTRS:
        nbytes += write_raw(os.path.join(d, f"{stem}.{name}.raw"),
                            blocks[name])

    origin = (float(zc[0]), float(y[0]), float(x[0]))
    spacing = (float(zc[1] - zc[0]), float(y[1] - y[0]), float(x[1] - x[0]))
    info = {
        "h": pr.h, "A": pr.A, "D": pr.D, "tau": tau,
        "Xout": pr.Xout, "Xe": pr.Xe, "Ce": pr.Ce, "Cpsi": pr.Cpsi,
        "eta0": pr.eta0, "eta1": pr.eta1, "bias": pr.bias,
        "eta_star": float(pr.eta_star()), "eta_max": eta_max,
        "Xmax_fac": Xmax_fac, "Rmax": float(Rmax), "Zmax": float(Zmax),
    }
    grid = grid_xml(stem, nx, ny, nz, origin, spacing, info, tval)

    with open(path, "w") as f:
        f.write('<Xdmf\n    Version="2">\n  <Domain>\n')
        f.write(grid)
        f.write("  </Domain>\n</Xdmf>\n")

    if verbose:
        report(path, tau, pr, x, y, zc, blocks["u"], blocks["speed"],
               Rmax, Zmax, nbytes)
    return grid


def build_series(path, times, pr, n=161, Xmax_fac=1.6, eta_max=0.95):
    """A CollectionType="Temporal" grid, one member per time.

    Each member is also written as a standalone .xdmf2, so a single snapshot can
    be opened on its own; the collection just re-hosts the same <Grid> blocks.
    """
    d = os.path.dirname(os.path.abspath(path)) or "."
    os.makedirs(d, exist_ok=True)
    stem = os.path.basename(path).rsplit(".", 1)[0]
    grids = []
    for i, t in enumerate(times):
        member = os.path.join(d, f"{stem}.{i:02d}.xdmf2")
        print(f"t = {t:.5f}")
        grids.append(build_xdmf(member, 1.0 - t, pr, n, Xmax_fac, eta_max,
                                tval=t))
    with open(path, "w") as f:
        f.write('<Xdmf\n    Version="2">\n  <Domain>\n'
                '    <Grid\n        GridType="Collection"\n'
                '        CollectionType="Temporal">\n')
        for g in grids:
            for line in g.splitlines(True):
                f.write("  " + line if line.strip() else line)
        f.write("    </Grid>\n  </Domain>\n</Xdmf>\n")
    print(f"  wrote {path}  (temporal collection, {len(times)} steps)")


# ----------------------------------------------------------------------------
# verification
# ----------------------------------------------------------------------------

def report(path, tau, pr, x, y, zc, U, SP, Rmax, Zmax, nbytes):
    dx = x[1] - x[0]
    dy = y[1] - y[0]
    dz = zc[1] - zc[0]
    ux, uy, uz = U[..., 0].astype(float), U[..., 1].astype(float), U[..., 2].astype(float)
    dux = np.gradient(ux, dx, axis=2)
    duy = np.gradient(uy, dy, axis=1)
    duz = np.gradient(uz, dz, axis=0)
    div = dux + duy + duz
    interior = (slice(1, -1), slice(1, -1), slice(1, -1))
    scale = SP.max() / min(dx, dy, dz)

    print(f"  wrote {path}  ({os.path.getsize(path)} B XML "
          f"+ {nbytes/1e6:.1f} MB in {len(ATTRS)} .raw files)")
    print(f"  tau={tau:.6g}  h={pr.h}  A={pr.A}  D={pr.D}")
    print(f"  box  r <= {Rmax:.4g}   |z| <= {Zmax:.4g}   l_z/l_r = {Zmax/Rmax:.3f}")
    print(f"  dividing layer at eta* = {pr.eta_star():.5f}  "
          f"(z = {pr.eta_star() * tau ** pr.D:+.5g}), just below z = 0")
    print(f"  max|u| = {SP.max():.6g}   (tau^-A = {tau**-pr.A:.6g})")
    print(f"  max|div u| / (max|u|/dx) = {np.abs(div[interior]).max()/scale:.3e}"
          "   <- discretisation only; the field is div-free by construction")


def check_scalings(pr):
    """Confirm the exponents of Sec. 3.1 numerically."""
    print("\nscaling checks (Sec. 3.1)")
    Xstar = 0.4 * pr.Xout
    print(f"  growth path z=0, r=sqrt(2 X* tau), X*={Xstar:.4g}:  "
          f"u_theta = q^-A E(X*), q = tau")
    prev = None
    print("      tau          u_theta         ratio     expected 4^A")
    for k in range(4, 12, 2):
        tau = 2.0 ** (-k)
        r = np.array([np.sqrt(2.0 * Xstar * tau)])
        z = np.array([0.0])
        _, utr, _, _, _, _, _ = cyl_fields(r, z, tau, pr)
        ut = (utr[0] * r[0]).item()
        if prev is None:
            print(f"    2^-{k:<3d} {ut:14.6g}")
        else:
            print(f"    2^-{k:<3d} {ut:14.6g}  {ut/prev:9.5f}   {2.0**(2*pr.A):12.5f}")
        prev = ut

    # radial pressure balance  d_r p = u_theta^2 / r
    tau = 2.0 ** -6
    print("  radial balance  d_r p = u_theta^2 / r   (2nd-order FD, so O(dr^2))")
    for npt in (400, 1600, 6400):
        r = np.linspace(0.05, 1.4, npt) * np.sqrt(2.0 * pr.Xout * tau)
        z = np.zeros_like(r)
        _, utr, _, p, _, _, _ = cyl_fields(r, z, tau, pr)
        ut = utr * r
        rel = (np.abs(np.gradient(p, r) - ut ** 2 / r).max()
               / np.abs(ut ** 2 / r).max())
        print(f"    {npt:5d} points   rel err = {rel:.2e}")

    # u_z(r,0) != 0 : the deliberate asymmetry of Sec. 2.1
    r0 = np.array([0.3 * np.sqrt(2.0 * pr.Xout * tau)])
    _, _, uz0, _, _, _, _ = cyl_fields(r0, np.array([0.0]), tau, pr)
    _, _, uzp, _, _, _, _ = cyl_fields(r0, np.array([+0.3 * tau ** pr.D]), tau, pr)
    _, _, uzm, _, _, _, _ = cyl_fields(r0, np.array([-0.3 * tau ** pr.D]), tau, pr)
    print(f"  u_z at eta = -0.3, 0, +0.3:  {uzm.item():+.4g}  {uz0.item():+.4g}  "
          f"{uzp.item():+.4g}   <- outflow both ways, nonzero at z=0")

    # U = V0 = 0 beyond Xout
    r1 = np.array([np.sqrt(2.0 * 1.3 * pr.Xout * tau)])
    urr, _, uz1, _, _, _, _ = cyl_fields(r1, np.array([0.2 * tau ** pr.D]), tau, pr)
    print(f"  at X = 1.3 Xout:  u_r = {(urr*r1).item():.3e}  u_z = {uz1.item():.3e}"
          "   <- purely azimuthal exterior")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--t", type=float, default=0.9, help="time; tau = 1 - t")
    ap.add_argument("--n", type=int, default=161, help="grid points per side")
    ap.add_argument("--h", type=float, default=0.01, help="the exponent h < 1/100")
    ap.add_argument("--Xout", type=float, default=0.12,
                    help="edge of the poloidal region in X; sets the l_z/l_r "
                         "aspect of the plotted box")
    ap.add_argument("--Xe", type=float, default=0.12, help="swirl core width in X")
    ap.add_argument("--Xmax", type=float, default=None,
                    help="box edge in X (default 1.6*Xout). With Xout pushed well "
                         "outside the box and Xe small, inflow persists to the frame "
                         "edge and u_theta/u_r ~ (1+2X/Xe)^-(1+h) varies strongly "
                         "across it: nearly radial outside, tight helices inside.")
    ap.add_argument("--Ce", type=float, default=1.0, help="swirl amplitude")
    ap.add_argument("--eta0", type=float, default=0.14,
                    help="thickness of the u_z sign change in eta; u_r ~ g'(eta), so a "
                         "thin layer confines the inflow to a sheet at z~0 while a thick "
                         "one spreads it over the core height")
    ap.add_argument("--eta1", type=float, default=0.55, help="axial extent of the jet in eta")
    ap.add_argument("--bias", type=float, default=0.16, help="upward bias so u_z(r,0) != 0")
    ap.add_argument("--Cpsi", type=float, default=1.0,
                    help="poloidal (streamfunction) amplitude; Ce/Cpsi large is "
                         "the swirl-dominated regime Re_theta >> Re_r of Sec. 3.1")
    ap.add_argument("-o", "--out", default=None,
                    help="path to the .xdmf2 file; .raw companions sit beside it")
    ap.add_argument("--series", action="store_true",
                    help="a temporal collection, t = 0.5 .. 0.96875")
    ap.add_argument("--no-checks", action="store_true")
    a = ap.parse_args()

    pr = Profiles(h=a.h, Xout=a.Xout, Xe=a.Xe, Ce=a.Ce, Cpsi=a.Cpsi,
                  eta0=a.eta0, eta1=a.eta1, bias=a.bias)
    xf = (a.Xmax / a.Xout) if a.Xmax else 1.6

    if a.series:
        out = a.out or "out/series.xdmf2"
        build_series(out, [1.0 - 2.0 ** -k for k in range(1, 6)], pr, n=a.n,
                     Xmax_fac=xf)
    else:
        out = a.out or f"out/core_t{a.t:.3f}.xdmf2"
        build_xdmf(out, 1.0 - a.t, pr, n=a.n, Xmax_fac=xf, tval=a.t)

    if not a.no_checks:
        check_scalings(pr)


if __name__ == "__main__":
    main()
